# Generated by Django 3.1.4 on 2021-01-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210123_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='homecontent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='homeimage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hometitle',
        ),
    ]
