# Generated by Django 3.1.4 on 2021-02-03 08:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210128_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=155)),
                ('views', models.IntegerField(default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('author', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
